import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { brotliCompressSync, constants } from 'node:zlib';
import { createHash } from 'node:crypto';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
process.chdir(root);
const LIBCIMBAR = 'bfb0c8e471820ae493cd3694ea6bed5d5ac06c37';
const OPENCV = '4.11.0';
const OPENCV_COMMIT = '31b0eeea0b44b370fd0712312df4214d4ae1b158';
function run(command, args, options = {}) {
  const result = spawnSync(command, args, { stdio: 'inherit', ...options });
  if (result.error) throw result.error;
  if (result.status !== 0) throw new Error(`${command} exited with ${result.status}`);
}
function checkout(url, dir, revision) {
  if (!fs.existsSync(`${dir}/.git`)) {
    fs.mkdirSync(dir, { recursive: true });
    run('git', ['init', dir]);
    run('git', ['-C', dir, 'remote', 'add', 'origin', url]);
    run('git', ['-C', dir, 'fetch', '--depth', '1', 'origin', revision]);
    run('git', ['-C', dir, 'checkout', '--detach', 'FETCH_HEAD']);
  }
}
checkout('https://github.com/sz3/libcimbar.git', 'third_party/libcimbar', LIBCIMBAR);
checkout('https://github.com/opencv/opencv.git', '.cache/opencv', OPENCV_COMMIT);
const revision = spawnSync('git', ['-C', 'third_party/libcimbar', 'rev-parse', 'HEAD'], { encoding: 'utf8' }).stdout.trim();
if (revision !== LIBCIMBAR) throw new Error(`Expected libcimbar ${LIBCIMBAR}, got ${revision}. Use a separate checkout for local modifications.`);
const cvRevision = spawnSync('git', ['-C', '.cache/opencv', 'rev-parse', 'HEAD'], { encoding: 'utf8' }).stdout.trim();
if (cvRevision !== OPENCV_COMMIT) throw new Error(`Expected OpenCV ${OPENCV_COMMIT}, got ${cvRevision}.`);

// Keep Emscripten's generated system libraries inside the workspace.
process.env.EM_CACHE = path.join(root, '.cache/emscripten');
const parallel = process.env.CIMBAR_JOBS || '4';
run('emcmake', ['cmake', '-S', '.cache/opencv', '-B', 'build/opencv',
  '-DCMAKE_BUILD_TYPE=MinSizeRel', '-DCMAKE_POLICY_VERSION_MINIMUM=3.5',
  '-DCMAKE_CXX_FLAGS=-fexceptions', '-DCMAKE_C_FLAGS=-fexceptions',
  '-DBUILD_LIST=core,imgproc', '-DBUILD_SHARED_LIBS=OFF', '-DBUILD_TESTS=OFF',
  '-DBUILD_PERF_TESTS=OFF', '-DBUILD_EXAMPLES=OFF', '-DBUILD_opencv_apps=OFF',
  '-DBUILD_opencv_js=OFF', '-DBUILD_JAVA=OFF', '-DBUILD_opencv_python3=OFF',
  '-DWITH_IPP=OFF', '-DWITH_ITT=OFF', '-DWITH_OPENCL=OFF', '-DWITH_PTHREADS_PF=OFF',
  '-DWITH_TBB=OFF', '-DWITH_OPENMP=OFF', '-DWITH_LAPACK=OFF', '-DWITH_EIGEN=OFF',
  '-DWITH_PROTOBUF=OFF', '-DWITH_ADE=OFF', '-DWITH_QUIRC=OFF',
  '-DWITH_JPEG=OFF', '-DWITH_PNG=OFF', '-DWITH_TIFF=OFF', '-DWITH_WEBP=OFF',
  '-DWITH_OPENJPEG=OFF', '-DWITH_OPENEXR=OFF', '-DWITH_JASPER=OFF',
  '-DOPENCV_DISABLE_THREAD_SUPPORT=ON', '-DCPU_BASELINE=', '-DCPU_DISPATCH=',
  '-DCV_ENABLE_INTRINSICS=OFF', '-DBUILD_ZLIB=OFF', '-DWITH_ZLIB=OFF',
  '-DCMAKE_INSTALL_PREFIX=' + path.join(root, 'build/opencv-install')]);
run('cmake', ['--build', 'build/opencv', '--parallel', parallel]);
run('cmake', ['--install', 'build/opencv']);
run('emcmake', ['cmake', '-S', 'native', '-B', 'build/decoder',
  '-DCMAKE_BUILD_TYPE=MinSizeRel', '-DOpenCV_DIR=' + path.join(root, 'build/opencv-install/lib/cmake/opencv4')]);
run('cmake', ['--build', 'build/decoder', '--parallel', parallel]);

fs.mkdirSync('miniprogram/workers/generated', { recursive: true });
fs.mkdirSync('miniprogram/wasm', { recursive: true });
const originalJS = fs.readFileSync('build/decoder/cimbar.js', 'utf8');
// Emscripten targets browsers, while WeChat exposes WXWebAssembly. Loading is
// supplied via instantiateWasm, so no fetch/DOM/URL/file-system shim is needed.
const js = '// Generated by npm run build:wasm; see native/ and THIRD_PARTY_NOTICES.md.\n' +
  'var WebAssembly = typeof WXWebAssembly !== "undefined" ? WXWebAssembly : globalThis.WebAssembly;\n' +
  'var performance = globalThis.performance || { now: function () { return Date.now(); } };\n' + originalJS;
fs.writeFileSync('miniprogram/workers/generated/cimbar.js', js);
const wasm = fs.readFileSync('build/decoder/cimbar.wasm');
const compressed = brotliCompressSync(wasm, { params: { [constants.BROTLI_PARAM_QUALITY]: 11 } });
fs.writeFileSync('miniprogram/wasm/cimbar.wasm.br', compressed);
const manifest = { libcimbar: revision, opencv: OPENCV,
  sha256: createHash('sha256').update(wasm).digest('hex'),
  wasmBytes: wasm.length, brotliBytes: compressed.length,
  emscripten: spawnSync('emcc', ['--version'], { encoding: 'utf8' }).stdout.split('\n')[0] };
fs.writeFileSync('miniprogram/wasm/build-info.json', JSON.stringify(manifest, null, 2) + '\n');
console.log('Decoder artifacts:', manifest);
run(process.execPath, ['scripts/collect-notices.mjs']);
